name: Continuous Integration
on: [pull_request]
jobs:
    Run-unit-tests:
        runs-on: ubuntu-latest
        container:
            image: node:21
        steps:
            - run:  npm run unit-tests